// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTPM2kXuDhcguy7L_mD1xzPsIOtoQ9jxs',
    appId: '1:81063651453:web:05babe894196a6aa442914',
    messagingSenderId: '81063651453',
    projectId: 'task-management-fbf7c',
    authDomain: 'task-management-fbf7c.firebaseapp.com',
    storageBucket: 'task-management-fbf7c.appspot.com',
    measurementId: 'G-GSCFG538R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByGKTNrqhlV2V3ft0NJYtqrK47K1qGE_g',
    appId: '1:81063651453:android:b5468d0f9646c550442914',
    messagingSenderId: '81063651453',
    projectId: 'task-management-fbf7c',
    storageBucket: 'task-management-fbf7c.appspot.com',
  );
}
